### ISSUE TITLE
CH 09: troublings with size option in plt.rc() method

### ISSUE THREAD

**Issue by MigueMarena** [wesm/pydata-book#103]
I run the following lines of code (as on page 278):

```python 
font_options = {'family' : 'monospace',
                'weight' : 'bold', 
                'size'   : 'small'}
plt.rc('font', **font_options) 
```
But the IPython interpreter shows me up a `ValueError` statement. Please take a look at this error message:

```python
Traceback (most recent call last):

  File "<ipython-input-29-9932f43ac628>", line 4, in <module>
    plt.rc('font', **font_options)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 303, in rc
    matplotlib.rc(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1262, in rc
    rcParams[key] = v

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 923, in __setitem__
    raise ValueError("Key %s: %s" % (key, str(ve)))

ValueError: Key font.size: Could not convert "small" to float
```

I also noticed that when I drop the las element on `font_options`, it works. Why is the case of such unexpected behavior of the code?

**Comment by sammjohnsn** [comment]
I came across the same ValueError statement when running the same lines of code (as on page 268 in the 2nd edition)

If you change "'small'" to an integer, for example '10', this will resolve the error: 

font_options = {'family' : 'monospace',
                          'weight' : 'bold',
                          'size' : '10'} 
plt.rc('font', **font_options)

**Comment by wesm** [comment]
Thanks for reporting, will fix in the book text

**Comment by Valentine520** [comment]
I also meet this problem, very confused.

**Comment by mcmurphy1991** [comment]
您好，
      您的邮件我已收到，我会尽快回复，谢谢。

**Comment by Monica6666** [comment]
已收到你的邮件，我会尽快回复！
