### ISSUE TITLE
Chapter 04, page 100: wrong semplification

### ISSUE THREAD

**Issue by LucaPaterlini** [wesm/pydata-book#104]
quote

> While perhaps not immediately obvious, this for loop can be converted into a nested
where expression:
np.where(cond1 & cond2, 0,
np.where(cond1, 1,
np.where(cond2, 2, 3)))
In this particular example, we can also take advantage of the fact that boolean values
are treated as 0 or 1 in calculations, so this could alternatively be expressed (though a
bit more cryptically) as an arithmetic operation:
result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)

```
cond1 = np.array([1, 0, 1, 0])
cond2 = np.array([0, 1, 1, 0])

# where syntax [1 2 0 3]
res = np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))
print(res)
# correct solution [1 2 0 3]
results = 3 - 2 * cond1 - 1 * cond2
print(results)
# book solution [-2 -1  0  0]
result = 1 * cond1 + 2 * cond2 + 3 * -(cond1 | cond2)
print(result)

```

**Comment by wesm** [comment]
Can you report errata on the O'Reilly website?

**Comment by wesm** [comment]
Will fix in source material
