### ISSUE TITLE
6.2 Binary Data Formats

### ISSUE THREAD

**Issue by norman-z** [wesm/pydata-book#111]
I copied the code from 'In [93]' to 'In [103]' to Google  Colab, and was given a ValueError for the code of 'In [103]', which said 'The file 'mydata.h5' is already opened, but not in read-only mode (as requested).'
Could somebody please help me with this question?
Thanks!
Norman

**Comment by wesm** [comment]
Not sure why this is happening in Colab but deleting the file and rerunning the examples will hopefully work.
