### ISSUE TITLE
minor typos in Ch02

### ISSUE THREAD

**Issue by Pejhan** [wesm/pydata-book#112]
I should firstly thank the author of this book @wesm for his major contributions to the Pandas community and also for this book which I am reading eagerly and thoroughly. 
so might I hint some minor typos in chapters I have covered so far:

p.36. The definition does not corespond with what the code is implying:
![image](https://user-images.githubusercontent.com/2239224/71561834-2ce43800-2a91-11ea-87d1-925f2bc2d778.png)

p.46. incorrect use of single quotations instead of double:
![image](https://user-images.githubusercontent.com/2239224/71561838-3ff70800-2a91-11ea-907e-d71ec38d2949.png)

**Comment by wesm** [comment]
Will be fixed in the 3rd edition. Thanks!
