### ISSUE TITLE
Ch12: TimeGrouper is deprecated

### ISSUE THREAD

**Issue by trakru** [wesm/pydata-book#121]
Under "Grouped Time Resampling"

`time_key = pd.TimeGrouper('5min')`
is incorrect/deprecated

the line should now read:
`time_key = pd.Grouper(freq='5min')`

**Comment by wesm** [comment]
Will fix. I'm overdue for an errata fixing sprint, I will get to it sometime in 2020

**Comment by wesm** [comment]
This is fixed in the 3rd edition
