### ISSUE TITLE
Conflicts when installing from miniconda.

### ISSUE THREAD

**Issue by guidorice** [wesm/pydata-book#127]
I am just getting started with the latest edition, but when installing from a miniconda 4.8.3 distribution, I found this was necessary (turning off strict channel priority)

```shell script
echo "channel_priority: false" > ~/.condarc
conda env create -f=requirements.txt python=3.6 -n pydata-book
conda activate pydata-book
conda install ipython jupyter
```
Just in case anyone runs across same trouble.

**Comment by wesm** [comment]
Thanks, indeed it looks like the requirements.txt needs to be updated. If you or someone want to submit a pull request bumping the versions it would be a big help, otherwise I can try to fix it up in the coming weeks

**Comment by wesm** [comment]
Fixed this in the 3rd-edition branch: https://github.com/wesm/pydata-book/blob/3rd-edition/requirements.txt
