### ISSUE TITLE
ch14 Bucketing Donation Amounts : normed_sums[:-2].plot(kind='barh') error

### ISSUE THREAD

**Issue by dukim73** [wesm/pydata-book#135]
bucket_sums = grouped.contb_receipt_amt.sum().unstack(0)
normed_sums = bucket_sums.div(bucket_sums.sum(axis=1), axis=0)
normed_sums
normed_sums[:-2].plot(kind='barh')

===========================================================================

TypeError                                 Traceback (most recent call last)
c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\arrays\interval.py in astype(self, dtype, copy)
    777         try:
--> 778             return np.asarray(self).astype(dtype, copy=copy)
    779         except (TypeError, ValueError) as err:

TypeError: int() argument must be a string, a bytes-like object or a number, not 'pandas._libs.interval.Interval'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\arrays\categorical.py in astype(self, dtype, copy)
    429             try:
--> 430                 astyped_cats = self.categories.astype(dtype=dtype, copy=copy)
    431             except (

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\indexes\interval.py in astype(self, dtype, copy)
    369         with rewrite_exception("IntervalArray", type(self).__name__):
--> 370             new_values = self._values.astype(dtype, copy=copy)
    371         return Index(new_values, dtype=new_values.dtype, name=self.name)

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\arrays\interval.py in astype(self, dtype, copy)
    780             msg = f"Cannot cast {type(self).__name__} to dtype {dtype}"
--> 781             raise TypeError(msg) from err
    782 

TypeError: Cannot cast IntervalIndex to dtype int32

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-21-1d4520b4efca> in <module>
      2 normed_sums = bucket_sums.div(bucket_sums.sum(axis=1), axis=0)
      3 normed_sums
----> 4 normed_sums[:-2].plot(kind='barh')

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\plotting\_core.py in __call__(self, *args, **kwargs)
    953                     data.columns = label_name
    954 
--> 955         return plot_backend.plot(data, kind=kind, **kwargs)
    956 
    957     __call__.__doc__ = __doc__

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\plotting\_matplotlib\__init__.py in plot(data, kind, **kwargs)
     59             kwargs["ax"] = getattr(ax, "left_ax", ax)
     60     plot_obj = PLOT_CLASSES[kind](data, **kwargs)
---> 61     plot_obj.generate()
     62     plot_obj.draw()
     63     return plot_obj.result

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\plotting\_matplotlib\core.py in generate(self)
    278         self._compute_plot_data()
    279         self._setup_subplots()
--> 280         self._make_plot()
    281         self._add_table()
    282         self._make_legend()

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\plotting\_matplotlib\core.py in _make_plot(self)
   1435             elif self.orientation == "horizontal":
   1436                 ax.yaxis.update_units(self.ax_index)
-> 1437                 self.tick_pos = ax.convert_yunits(self.ax_index).astype(np.int)
   1438             self.ax_pos = self.tick_pos - self.tickoffset
   1439 

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\indexes\category.py in astype(self, dtype, copy)
    374     @doc(Index.astype)
    375     def astype(self, dtype, copy=True):
--> 376         res_data = self._data.astype(dtype, copy=copy)
    377         return Index(res_data, name=self.name)
    378 

c:\users\admin\anaconda3\envs\dwkim\lib\site-packages\pandas\core\arrays\categorical.py in astype(self, dtype, copy)
    434             ):
    435                 msg = f"Cannot cast {self.categories.dtype} dtype to {dtype}"
--> 436                 raise ValueError(msg)
    437 
    438             astyped_cats = extract_array(astyped_cats, extract_numpy=True)

ValueError: Cannot cast interval[int64] dtype to <class 'int'>

**Comment by wesm** [comment]
Thanks for reporting — I will look into this and try to fix (I would expect this code to keep working — it seems like a bug in the interface between pandas and matplotlib). cc @jreback if you know

**Comment by wesm** [comment]
This code example is fixed in the 3rd edition
