### ISSUE TITLE
How to download files?

### ISSUE THREAD

**Issue by Panitzin** [wesm/pydata-book#139]
Hi

I am new to GitHub. I bought the Kindle version of Wes book: "Python for Data Analysis". 

I am having problems downloading files from this repository, could you please help me?

Thank you.

Pano.

**Comment by PauloHFS** [comment]
![image](https://user-images.githubusercontent.com/36555768/129495983-57d95d93-206c-4bd9-9227-df4fe2d24eba.png)
it's simple, click on **Code** then **Download ZIP**.

**Comment by Panitzin** [comment]
Hey Paolo

It works !!! thank you.
Pano
