### ISSUE TITLE
ch08 - error in example

### ISSUE THREAD

**Issue by anicelysantos** [wesm/pydata-book#140]
Hi, i am having the following error when running this example. 

`pd.concat([s1,s4], axis=1, join_axes=[['a','c','b','e']])`

`TypeError: concat() got an unexpected keyword argument 'join_axes'`

Can someone help me please?
I saw that this option was discontinued, but I don't know how to adapt the example.

**Comment by wesm** [comment]
I believe it's 

```python
pd.concat([s1,s4], axis=1).reindex(columns=['a','c','b','e'])
```

I'm working (slowly) on the 3rd edition and will fix this along with fixing up any other broken / deprecated code examples
