### ISSUE TITLE
np.random.randn, np.random.randint have been replaced with a new paradigm using a generator

### ISSUE THREAD

**Issue by wrongways** [wesm/pydata-book#149]
See: https://numpy.org/doc/stable/reference/random/index.html#random-quick-start

Replace `np.random.seed()` with `rng = np.random.default_rng()`
Replace `np.random.randint()` with `rng.integers()`
Replace `np.random.randn()` with `rng.standard_normal()`
Replace `np.random.normal()` with `rng.normal()`

**Comment by wesm** [comment]
This is done in the 3rd edition
