### ISSUE TITLE
Page numbers for online version

### ISSUE THREAD

**Issue by DavisDaddy** [wesm/pydata-book#153]
Probably a dumb question, but I've just started looking at the online version of the third edition, and I've found a couple of possible errors.  If I go to the O'Reilly site (http://oreilly.com/catalog/0636920023784/errata) I'm asked to supply a page number for the problem I'm trying to report.  This is reasonable enough, except that I don't see page numbers in the web version.  What am I missing?  Thanks.

**Comment by wesm** [comment]
You can just indicate the chapter number and section heading in your errata comment. Thanks for reporting errata
