### ISSUE TITLE
Third version typo on the website

### ISSUE THREAD

**Issue by yibenhuang** [wesm/pydata-book#157]
Chapter 5, Paragraph 2, at this link: https://wesmckinney.com/book/pandas-basics.html

> While pandas adopts many coding idioms from NumPy, the **biggestabout** difference is that pandas is designed for working with tabular or heterogeneous data.

The word **biggestabout** seems to be a typo, where it should just be biggest?

**Comment by mcmurphy1991** [comment]
您好，
      您的邮件我已收到，我会尽快回复，谢谢。

**Comment by Monica6666** [comment]
已收到你的邮件，我会尽快回复！

**Comment by wesm** [comment]
Thanks — we will fix this.
