### ISSUE TITLE
3rd Ed | Ch 5 | Correlation and Covariance code block

### ISSUE THREAD

**Issue by TomPham97** [wesm/pydata-book#159]
The following [code block](https://wesmckinney.com/book/pandas-basics.html#pandas_corr_cov:~:text=Since%20MSFT%20is,285%5D%3A%200.49976361144151144) from the 3rd edition needs to be changed to
```Python
returns.MSFT.corr(returns["IBM"])
```

**Comment by wesm** [comment]
I decided to use the `returns['MSFT']` (and avoid the dot-attribute access) in the 3rd edition
