### ISSUE TITLE
Chaper 2 - Running the IPython Shell

### ISSUE THREAD

**Issue by tidyeval** [wesm/pydata-book#161]
The first two lines are Python code statements; the second statement creates a variable named data that refers to a newly created Python dictionary. The last line prints the value of data in the console.

CORRECTION: data is a list not dictionary

In [5]: import numpy as np

In [6]: data = [np.random.standard_normal() for i in range(7)]

In [7]: data

**Comment by renga17** [comment]
Hi
Please unsubscribe me from your mailing list.

Thanks
Renga

**Comment by wesm** [comment]
This will be fixed shortly on https://wesmckinney.com/book and in the next release of the print 3rd edition
