### ISSUE TITLE
One image on the website is broken

### ISSUE THREAD

**Issue by Hofer-Julian** [wesm/pydata-book#162]
One image on the website is broken.
See here: https://wesmckinney.com/book/numpy-basics.html#fig-figure_ndarray_indexing

**Comment by mcmurphy1991** [comment]
您好，
      您的邮件我已收到，我会尽快回复，谢谢。

**Comment by Monica6666** [comment]
已收到你的邮件，我会尽快回复！

**Comment by wesm** [comment]
fixed!

**Comment by Hofer-Julian** [comment]
Thanks!
We've already bought a physical copy. Looking forward to its arrival :)
