### ISSUE TITLE
Book claims that matrix multiplications require using a function

### ISSUE THREAD

**Issue by Hofer-Julian** [wesm/pydata-book#163]
The book claims [here](https://wesmckinney.com/book/numpy-basics.html#numpy_linalg):

> Multiplying two two-dimensional arrays with * is an element-wise product, while matrix multiplications require using a function.

Just to later introduce the `@` operator.
I assume that is a remnant of former editions of the book.

**Comment by wesm** [comment]
Thanks. I will correct this!
