### ISSUE TITLE
what is #! ipython suppress id ?

### ISSUE THREAD

**Issue by LeiYangGH** [wesm/pydata-book#168]
i see this comment in almost every notebook.
but searching the string doesn't bring me any useful documents.
how are they generated and what are they used for?

**Comment by DWOODl** [comment]
您好！我是林新，您的邮件已收到，我会尽快回复，感谢您的来信~

**Comment by wesm** [comment]
It’s just an instruction for the homegrown tool I use to build the book (which isn’t used for anything else). I will try to remove these comments from these files since it is a bit distracting.

**Comment by LeiYangGH** [comment]
thanks for the explainations!

**Comment by wesm** [comment]
Just confirming that I updated all the notebook files in https://github.com/wesm/pydata-book/commit/f1757b857b5f1fc5cfcfd0fab37bf219bf4595ec

**Comment by DWOODl** [comment]
您好！我是林新，您的邮件已收到，我会尽快回复，感谢您的来信~
