### ISSUE TITLE
typo in section Removing Duplicates

### ISSUE THREAD

**Issue by codeandstats** [wesm/pydata-book#176]
Regarding [section](https://wesmckinney.com/book/data-cleaning.html#prep_clean_deduplicate)

I believe the `False`  in the following sentence should be a `True` ? 

Relatedly, `drop_duplicates` returns a DataFrame with rows where the `duplicated` array is `False` filtered out

**Comment by wesm** [comment]
Thanks for the report — I think the issue is the interpretation of "filtered out". For some this might mean "included" and for others "excluded". I will update the text to be clear that it means "excluded".
