### ISSUE TITLE
Failure to open a csv-file

### ISSUE THREAD

**Issue by Riverise** [wesm/pydata-book#182]
It seems that there is a problem with the file 'datasets/fec/p00000001-All.csv', unable to be opened or downloaded.

**Comment by cybergeekgyan** [comment]
Hey @Riverise I have downloaded the dataset it seems to be working perfectly fine, you can download again

**Comment by wesm** [comment]
I can confirm that there is no issue with the file, but keep in mind that file names are case sensitive!

**Comment by Riverise** [comment]
Thank you all~
