### ISSUE TITLE
In chapter 2, print(template) is not giving expected answer as the original string never get changed by this format

### ISSUE THREAD

**Issue by sde-nitin-chaudhary** [wesm/pydata-book#183]
Your Code:
template="{0:.2f} {1:s}are worth US${2:d}"
template.format(4.5667,'Argentine Pesos',1)
print(template)

Output Your Code:
{0:.2f} {1:s}are worth US${2:d}
 
Updated Code:
template="{0:.2f} {1:s}are worth US${2:d}".format(4.5667,'Argentine Pesos',1)
print(template)

Output Updated Code:
4.57 Argentine Pesosare worth US$1

**Comment by DWOODl** [comment]
您好！我是林新，您的邮件已收到，我会尽快回复，感谢您的来信~

**Comment by wesm** [comment]
This is fixed in the 3rd edition, you can see the new code here:

https://wesmckinney.com/book/python-basics#scalar_strings

**Comment by DWOODl** [comment]
您好！我是林新，您的邮件已收到，我会尽快回复，感谢您的来信~
