### ISSUE TITLE
Couple of chapters as demo for Quarto learning

### ISSUE THREAD

**Issue by AlfonsoRReyes** [wesm/pydata-book#189]
Hi Wes,
amazing book! Thank you for sharing.
I have started to learn Quarto and your book if one of the few -or the only one- that uses Jupyter files for the creation of a book. I have cloned your repo for this book but I am unable to find any source code for the book construction. Is there a chance that you could share a couple of chapters where we could see how you run `.ipynb` notebooks in Quarto?
We will appreciate it very much.

**Comment by s2t2** [comment]
Yes, I am looking for the _quarto.yml file as well.

**Comment by wesm** [comment]
Unfortunately, I'm not able to share the Quarto source files that are used to render the book for the web. I actually have converted the Docbook XML files (which are the definitive version of the book) to Quarto .qmd files and then used Quarto to generate the website from the generated .qmd files.
