### ISSUE TITLE
ch11.ipynb Small issue with the to_index 

### ISSUE THREAD

**Issue by alexnsaunders** [wesm/pydata-book#32]
Under Decile and Quantile analysis the to_index function finds the max of a return index and replaces with 1. I believe it should be looking for the first non NaN and replacing the previous entry with a 1.

def to_index(rets):
    index = (1 + rets).cumprod()
    first_loc = max(index.index.get_loc(index.idxmax()) - 1, 0)
    index.values[first_loc] = 1
    return index

change to:

first_loc = max(index.index.get_loc(index.notnull().argmax()) - 1,0)

Seems to work - there was a proposed change in the O'Reilly Errata but that solution doesn't count back 1 so effectively ignores the first day return. Hope this helps, I am new to Python; great book.

**Comment by JeanMiMi** [comment]
The proposed change indeed allows to generate the graph printed in the book. Thanks
