### ISSUE TITLE
crosstab not working because the 'size' variable is being treated as a number 

### ISSUE THREAD

**Issue by michaelreinhard** [wesm/pydata-book#39]
Hi Wes, 

I switched from SPSS to Pandas and one of the few things I miss about SPSS is the way it did crosstabs. 

I have been trying to follow along in the notebook for chapter 8 on visualization and there is one point where you make a crosstab with the tips data frame with the code: 

party_counts = pd.crosstab(tips.day, tips.size) and you get this nice crosstab table of the number of cases by day and party size (it doesn't paste well): 

In [69]: party_counts = pd.crosstab( tips.day, tips.size) In [70]: party_counts Out[ 70]: size 1 2 3 4 5 6 day Fri 1 16 1 1 0 0 Sat 2 53 18 13 1 0 Sun 0 39 15 18 3 1 Thur 1 48 4 5 1 3

McKinney, Wes (2012-10-08). Python for Data Analysis (Kindle Locations 5544-5547). O'Reilly Media. Kindle Edition. 

I have tried to fix this by making size into a categorical variable but it has not worked. What I get is a that the days are correctly displayed but the party size variable gets collapsed to the mean, 1708, one column. 

I can try to copy it into this text box: 

pd.crosstab(tips.day, tips.size, margins=True)
Out[14]:
col_0	1708	All
day		
Fri	19	19
Sat	87	87
Sun	76	76
Thur	62	62
All	244	244

Here is the link to my github account. 

https://github.com/michaelreinhard/pydata-book/blob/master/ch08.ipynb

I just can't figure out what I am doing wrong. I feel like I am doing just what you do in your code and I am working from your notebook from github. Any advice or suggestions you could make for where to look for the answer or to investigate further would be greatly appreciated. Thanks, 

Michael Reinhard

**Comment by wesm** [comment]
hi @michaelreinhard, since the book was written `size` has been added a property to `pandas.DataFrame` which supercedes the `'size'` column name in the data. 

```python
n [12]: tips.size
Out[12]: 1708

In [13]: pd.crosstab(tips.day, tips['size'])
Out[13]: 
size  1   2   3   4  5  6
day                      
Fri   1  16   1   1  0  0
Sat   2  53  18  13  1  0
Sun   0  39  15  18  3  1
Thur  1  48   4   5  1  3
``` 

sorry about the foul-up. hope this helps

**Comment by michaelreinhard** [comment]
Yes! Thank you so much! I really appreciate it. 
Michael
