### ISSUE TITLE
CAN'T FIND EPD_FREE-7.3-1.DMG

### ISSUE THREAD

**Issue by Homosum** [wesm/pydata-book#50]
I  followed the website-instruction , still can't find the epd_free-7.3-1.dmg install-package on Enthought.com . What's EPD used for? Can anyone share a download-site,if not, any substitute can I use to go on within pydata-book?

**Comment by wesm** [comment]
I recommend you install Anaconda from https://www.continuum.io/downloads. Thanks

**Comment by wesm** [comment]
Second edition recommends installing Anaconda or miniconda (https://conda.io/miniconda)
