### ISSUE TITLE
Clarification of NumPy Boolean Indexing Copy Behavior

### ISSUE THREAD

**Issue by pglezen** [wesm/pydata-book#52]
Page 100 of the 2nd edition describes boolean indexing of NumPy arrays.  The following remark is made in the middle of the page.

> Selecting data from an array by boolean indexing *always* creates a copy of the data

But then the next two examples demonstrate assignments to a boolean-indexed array.  If boolean indexing created copies, wouldn't the original array (`data` in the examples) be unchanged?  Wouldn't the assignment apply to the copy rather than the original?

I verified that indeed, if I perform the following:

```
mask = data < 0
data2 = data[mask]
data2 = 8
```
Then `data` is left unchanged.  So `data2` does indeed contain a copy and assignment to it does not affect `data`.  In this sense, the statement is correct.  But when `data[mask]` appears on the lefthand side (i.e. as an *lvalue*), no copy is created.  It is assigned in-place.

The upshot of this issue is that a small clarification might be in order for that statement.

**Comment by ghost** [comment]
When you do data[mask] = xyz it does not create a copy but instead calls data.__setitem__(...) which modifies in place (similar to fancy indexing).

**Comment by wesm** [comment]
Thanks. Indeed I will clarify this in the text
