### ISSUE TITLE
Cannot find all table tags in ch06

### ISSUE THREAD

**Issue by khanh96le** [wesm/pydata-book#54]
Issue:
- Cannot find all table tags using **find_all(".//table")** in page: http://finance.yahoo.com/q/op?s=AAPL+Options

Reproduce:
- Running In [46] of ch06.ipynb

**Comment by wesm** [comment]
The format of finance.yahoo.com has changed, sorry about this. I am removing this example in the 2nd edition of the book

**Comment by khanh96le** [comment]
Thank you for quick responding!

**Comment by wesm** [comment]
Fixed in 2nd ed
