### ISSUE TITLE
Ch02, i have no %paste and %cpaste, i want add them, how can i do?

### ISSUE THREAD

**Issue by chaos-zhou** [wesm/pydata-book#56]
like title, i want add function about %paste and %cpaste in my magic folder, but i can't find them in web, how can i do, pls hlep me, thank you

**Comment by wesm** [comment]
These functions are built-in to IPython. They are not available in Jupyter

**Comment by chaos-zhou** [comment]
yeah, i know. If i call IPython from cmd, i can use them, but i call IPython from Enthought Canopy i can't found %paste and %cpaste. BTW, If I follow the book example of writing code, should i use cmd or Enthought Canopy? or another tool for Python? 
thank you

**Comment by wesm** [comment]
I think in Canopy that the paste and cpaste functions are not required -- you can press `Ctrl-V` to paste directly from the clipboard.

If that does not work for you, I suggest using Jupyter notebooks directly, either from Canopy or from another Python distribution (e.g. Anaconda)

**Comment by chaos-zhou** [comment]
thank you very much!
