### ISSUE TITLE
XML and HTML: Web scraping

### ISSUE THREAD

**Issue by jingw222** [wesm/pydata-book#57]
Hi, Wes. In Chapter 6, there's one part that's kind of outdated:

`XML and HTML, Web scraping`
`NB. The Yahoo! Finance API has changed and this example no longer works`

Do you mind revise that part and present us a v2.0?

**Comment by wesm** [comment]
I am removing the Yahoo! Finance example (since who knows what Yahoo! will look like a few years from now even) for the 2nd edition

**Comment by duncangh** [comment]
@jingw222 you can still replicate the exercises in Python for Data Analysis using the pandas_datareader library. See https://github.com/pydata/pandas-datareader

>>>import pandas_datareader as pdr
>>>pdr.get_data_yahoo('AAPL')

**Comment by wesm** [comment]
Fixed in 2nd edition
