### ISSUE TITLE
False claim about np.fabs()

### ISSUE THREAD

**Issue by g-leech** [wesm/pydata-book#62]
Hello,

In Table 4-3, you say to 

> Use `fabs` as a faster alternative for non-complex-valued data

However, I don't think `fabs` is faster [in any case](https://stackoverflow.com/questions/21994052/abs-vs-fabs-speed-difference-and-advantage-of-fabs). Amortized runs show about 15% slower than `abs()` for ints, and 1% slower for floats.

**Comment by wesm** [comment]
Thanks. I would have to look back at an older version of NumPy but I think this may have been true 5 or 6 years ago. Recent versions of NumPy include quite a bit of work on SIMD optimizations so it's possible that explains the difference

**Comment by wesm** [comment]
Will be fixed in 2nd edition
