### ISSUE TITLE
Trying to load Yahoo finance data

### ISSUE THREAD

**Issue by chrisrb10** [wesm/pydata-book#65]
Hi,

I am trying to load the Yahoo finance data from the .pkl files to use in place of the ```'get_data_yahoo```  example in the Correlation and Covariance section of Ch05.

But I'm struggling to work out how to unpack the data to use in the example  - do you have sample code of how to do this?

thanks

**Comment by wesm** [comment]
You can use `pandas.read_pickle` for this, does that work?

**Comment by chrisrb10** [comment]
That works perfectly - many thanks.
