### ISSUE TITLE
Advanced pandas chapter rendering issue

### ISSUE THREAD

**Issue by learnbyexample** [wesm/pydata-book#68]
Link: http://nbviewer.jupyter.org/github/pydata/pydata-book/blob/2nd-edition/ch12.ipynb

Snapshot of what I see
![adv_pandas_issue](https://user-images.githubusercontent.com/17766317/30951135-fa8229c4-a43e-11e7-8eaa-b451d43c827f.png)

**Comment by wesm** [comment]
Fixed. Thank you!
