### ISSUE TITLE
Time series chapter: strftime and strptime don't use the same format codes

### ISSUE THREAD

**Issue by jabranham** [wesm/pydata-book#76]
In the part discussing converting datetime objects from strings, you say that `strptime` uses the same format codes as `strftime`, but that's not quite right:

```python
value = '2011-01-03'
stamp = datetime.strptime(value, '%Y-%m-%d')  # works
datetime.strptime(value, '%F')  # ValueError: 'F' is a bad directive in format '%F'
datetime.strftime(stamp, '%F')  # works
```

**Comment by wesm** [comment]
Thanks for bringing this up. Could you submit an errata in the O'Reilly portal? http://shop.oreilly.com/product/0636920050896.do

**Comment by jabranham** [comment]
Done

**Comment by wesm** [comment]
thank you!
