### ISSUE TITLE
Can not open Ipython Notebooks

### ISSUE THREAD

**Issue by YuanEric88** [wesm/pydata-book#77]
Why can't I open or download Ipython Notebooks in the file?

**Comment by wesm** [comment]
Did you try downloading one of (based on what version of the book you're reading)?

* https://github.com/wesm/pydata-book/archive/1st-edition.zip
* https://github.com/wesm/pydata-book/archive/2nd-edition.zip

**Comment by YuanEric88** [comment]
Hi, 
Thank you. I have downloaded the version I preferred.
Best,
Yuan




发自网易邮箱大师


On 12/14/2017 12:11，Wes McKinney<notifications@github.com> wrote：

Did you try downloading one of (based on what version of the book you're reading)?

https://github.com/wesm/pydata-book/archive/1st-edition.zip
https://github.com/wesm/pydata-book/archive/2nd-edition.zip
