### ISSUE TITLE
ch7 7.3 String Manipulation  

### ISSUE THREAD

**Issue by falseform** [wesm/pydata-book#80]
Vectorized String Functions in pandas

In [174]: matches = data.str.match(pattern, flags=re.IGNORECASE)
In [175]: matches
Out[175]:
Dave True
Rob True
Steve True
Wes NaN
dtype: object``

does the str.match   correct? 

in the past 

it  is   
Dave     (dave, google, com)
Rob        (rob, gmail, com)
Steve    (steve, gmail, com)
Wes                        NaN
dtype: object

**Comment by wesm** [comment]
The API in pandas did change IIRC. `str.extract` does what `str.match` used to do

**Comment by willy810710** [comment]
Finally, I got the issue.
Thank you for helping, Wesm.

**Comment by willy810710** [comment]
By the way, is it possible to get only a list or any format of the name for each data point?
The expected return is like: dave, rob, steve, nan.
Thank you.
