### ISSUE TITLE
Join to translation English to Indonesian 

### ISSUE THREAD

**Issue by rabooe** [wesm/pydata-book#81]
hello Mr., I am a translator, I want to translate English into Indonesian, Because the majority of Indonesian people do not understand English.. I will be sincere if I am in trust

**Comment by wesm** [comment]
hi @rabooe -- I am not sure if a Bahasa translation is planned for the book yet, but I'd be happy to put you in touch with the O'Reilly folks if you'd like to be involved. Please contact me on LinkedIn or via Twitter direct message. Thanks!
