### ISSUE TITLE
Typo in book 2nd ed. (Ch 3, p58, slicing)

### ISSUE THREAD

**Issue by RoutineRoute** [wesm/pydata-book#82]
The example for slicing uses expression
seq=[7, 2, 3, 7, 5, 6, 0, 1]
for seq[-6:-2] the book says that result should be  [6, 3, 5, 6], but it is [3, 7, 5, 6]. 
Just to let you know about that issue.

**Comment by wesm** [comment]
Would you mind submitting an erratum on http://shop.oreilly.com/product/0636920050896.do? Thanks!
