### ISSUE TITLE
How to read CSV data from variable into PD DataFrame

### ISSUE THREAD

**Issue by ghost** [wesm/pydata-book#83]
Hello Wes,

Love your book, but I'm stumped by not being able to just read a CSV "variable" into a PD dataframe. 

In my case, I get the IRIS data (for starting point of the project)  POSTed into a Flask web service. (Later I'll use my own CSV data.)

I then extract the text from the Flask's POST request.values. All good. But at that point, I can't figure out how to get the pandas dataframe like your pd.read_csv does. 

I'm assuming reading a variable into a PD DF should be difficult since it seems like an obvious use-case.

--------

I tried wrapping with io.StringIO(csv_data), then following up with read_csv on that variable, but that doesn't work either.

I'm writing since I can't find a page in your book where it describes how to simply read a variable into a PD dataframe.

Note: I also tried things like ...

data = pd.DataFrame(csv_data, columns=['....'])

but got nothing but errors (for example, "constructor not called correctly!")

--

I guess my problem is that your (excellent) book shows how to create DataFrames from entered data, and it shows how to create a DataFrame using files, but not (that I can find) how to create a DataFrame using csv data...in a variable.

I am hoping for a simple method to call that can infer the columns and names and create the DataFrame for me, from a variable, without me needing to know a lot about Pandas (just to read the dataset, anyway).

I'm relatively new to Python (a few months) so I'm probably missing something extremely obvious...

Thanks very much,

**Comment by wesm** [comment]
Could you ask this question on StackOverflow? Thanks!
