### ISSUE TITLE
ch6: XML and HTML, Web scraping 

### ISSUE THREAD

**Issue by kevinblog** [wesm/pydata-book#89]
Hello,

I got a problem when I ran the code of this section on Jupyter Notebook.

It was running all the time and couldn't get the results.

I wonder if there is anything wrong with my code? How can I fix them? 

![image](https://user-images.githubusercontent.com/16619656/41448762-3585680c-708f-11e8-8589-c48cc761d79e.png)

Looking forward to your reply.

**Comment by wesm** [comment]
hi @FENG06 since this part was written in 2012, Yahoo! has changed their website. You might be able to get it working with a new url like https://finance.yahoo.com/quote/AAPL/options?p=AAPL

**Comment by kevinblog** [comment]
@wesm Thanks a lot, it does work after changing the code with new Yahoo url.
