### ISSUE TITLE
Not able to download datasets

### ISSUE THREAD

**Issue by snwkit696** [wesm/pydata-book#90]
I purchased "Python for Data Analysis" and am not able to download the datasets for the book.  Has this information moved or do I have to register?  I'm on Chapter 6, so I'm new and learning how to download files correctly to my Jupyter notebook and apologize if this seems like a novice question.  
Thank you.

**Comment by olisteadman** [comment]
@snwkit696 could you show what you've tried already?

(eg any lines of code or processes you've gone through; this would help know what's not working and how we can address it. Screenshots always useful too.)

**Comment by wesm** [comment]
Does this link work for you? https://github.com/wesm/pydata-book/archive/2nd-edition.zip

**Comment by snwkit696** [comment]
Yes, it does.  Thank you for sending the link, much appreciated!
 
--------------------------------------------
On Wed, 7/4/18, Wes McKinney <notifications@github.com> wrote:

 Subject: Re: [wesm/pydata-book] Not able to download datasets (#90)
 To: "wesm/pydata-book" <pydata-book@noreply.github.com>
 Cc: "AwechMeehan" <snowkittypb@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, July 4, 2018, 8:37 AM
 
 Does this link work for you? https://github.com/wesm/pydata-book/archive/2nd-edition.zip
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
