### ISSUE TITLE
Issue Openning Files

### ISSUE THREAD

**Issue by nabs825** [wesm/pydata-book#91]
I have downloaded all the files in this repository. When I try to work with them, for example using the code `list(open(('examples/ex3.txt')`, I consistently receive the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'ex3.txt'`

Do you know of any potential causes for this issue? Does it have to do with the directory that I have saved my download to?

**Comment by olisteadman** [comment]
@nabs825 Have you tried putting the full path to the file? It’d be good if you can paste here the command that yielded the error text.

**Comment by wesm** [comment]
@nabs825 you may not be running the Jupyter notebook or IPython from the same directory where the files are located. You can find out by running 

```
!pwd
```

**Comment by nabs825** [comment]
@wesm what are you implying I run `!pwd` in? Also, is there documentation in the book that provides a detailed tutorial of how to run Jupyter notebook such that the files are readily available? I initially skipped chapters 2 and 3 which I think caused me to miss some basic info. I looked over the Jupyter section and have been having issues, but I may have missed something.

**Comment by wesm** [comment]
I meant to run that command in IPython or Jupyter. I would suggest reviewing these tools as they are very helpful for working through the rest of the book

**Comment by liuchener** [comment]
> 
> 
> I have downloaded all the files in this repository. When I try to work with them, for example using the code `list(open(('examples/ex3.txt')`, I consistently receive the following error:
> 
> `FileNotFoundError: [Errno 2] No such file or directory: 'ex3.txt'`
> 
> Do you know of any potential causes for this issue? Does it have to do with the directory that I have saved my download to?

I can't download the datasets now, so I want to ask wether you can send  a copy of the data. I will appreciate you so much

**Comment by kekenalog** [comment]
你需要查看一下看的第几个章节，example一般都是ch[02-14]中某个一个章节文件包中
