### ISSUE TITLE
ch7 7.3 String Manipulation

### ISSUE THREAD

**Issue by GengBin414** [wesm/pydata-book#92]
Vectorized String Functions in pandas

I can't figure out the meaning of the following code, can you explain it further: 

In [176]: matches .str.get(1)
Out[176]:
Dave NaN
Rob NaN
Steve NaN
Wes NaN
dtype: float64

In [177]: matches .str[0]
Out[177]:
Dave NaN
Rob NaN
Steve NaN
Wes NaN
dtype: float64

**Comment by wesm** [comment]
Looks like errata; I'm about to do some corrections of errata so I'll let you know when I get to this one

**Comment by GengBin414** [comment]
Thanks for your prompt reply!

**Comment by wesm** [comment]
This will be fixed in the next printing

**Comment by Wendy-mhwu** [comment]
Has it been changed? My second edition book is still this, I can't figure out, it gave error message.

**Comment by wesm** [comment]
Reopening until I can confirm this is resolved and also fixed in the notebooks here

**Comment by KXCY-AI** [comment]
Got the same error output, and waiting for the way to walk around.

**Comment by wesm** [comment]
Will be fixed in the 3rd edition (notebooks will be updated in this repo when it's closer to publication)
