### ISSUE TITLE
A newer's trouble！

### ISSUE THREAD

**Issue by tracy2050** [wesm/pydata-book#94]
I am a newer of python from china with poor English！According the tips on the book <Python for Data Analysis>:"You can find data files and related material for each chapter is available in this book's GtiHub repository at http://github.com/wesm/pydata-book." I went here so many times,and hava found the data files and material so many times ,but I lost it! I am so anxiety,and too eager to need your help!Please!
Thanks very much!

**Comment by wesm** [comment]
Try this link https://github.com/wesm/pydata-book/archive/1st-edition.zip. If you are reading the 2nd edition please replace 1st-edition in the link with 2nd-edition
