### ISSUE TITLE
Hello, can you help me check the code?Why doesn't the title field appear in movie?thank you

### ISSUE THREAD

**Issue by ghost** [wesm/pydata-book#95]
![qq 20180904181457](https://user-images.githubusercontent.com/42964253/45025629-92c3d980-b06e-11e8-808b-a065d5d49a09.png)

**Comment by wesm** [comment]
Try setting `pd.options.display.max_columns = 20`. I referenced a pandas issue on GitHub where we are discussing this

**Comment by ghost** [comment]
Use it often. It didnt fix my problem though

**Comment by wesm** [comment]
I'll try to fix this when fixing other errata
