### ISSUE TITLE
Error on page 352.

### ISSUE THREAD

**Issue by charbelsako** [wesm/pydata-book#98]
The 2 code examples are the same. 

`In[216]: ts.resample('5min', closed='right').sum()`

`In[217]: ts.resample('5min', closed='right').sum()`

216 should be without the `closed='right'`

**Comment by wesm** [comment]
Can you report on O'Reilly's errata system? Thank you!

**Comment by charbelsako** [comment]
OK. As soon as I figure out where that Is. 😅

**Comment by charbelsako** [comment]
Submitted or the errata system

**Comment by wesm** [comment]
thanks!
